config/routes.rb
BaseApp::Application.routes.draw do

  resources :users, :only => [ :show, :new, :create, :edit, :update ]
  resources :sessions, :only => [ :new, :create, :destroy ]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w[admin]

  attr_accessible :username, :email, :password, :password_confirmation
  has_secure_password
  validates :username,  :presence => true,
                        :length => { :within => 5..50 },
                        :uniqueness => { :case_sensitive => false }
  validates :email,     :presence => :true,
                        :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i },
                        :uniqueness => { :case_sensitive => false }
  validates :password,  :presence => true,
                        :length => { :within => 6..40 }
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask || 0) & 2**ROLES.index(r)).zero?
    end
  end
  
  def has_role?(role)
    roles.include?(role)
  end

  def admin?
    has_role?("admin")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), :notice => "Logged in as #{user.username}."
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Congratulations!  You have successfully signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

 def title
    base_title = "Base Application"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end 
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg.html_safe) }
        content_tag(:h2, options[:header_message].html_safe) + content_tag(:p, options[:message].html_safe) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_roles
    User::ROLES
  end
end

app/views/layouts/_admin.html.erb
<% if current_user && current_user.admin? %>
<div id="admin_toolbar">
  <ul>
  	<li><strong>Administer:</strong></li>
  	<li><%= link_to "Users", users_path %></li>
  </ul>
</div>
<% end %>

app/views/layouts/_header.html.erb
<nav>
	<ul>
    <% if current_user %>
		  <li>Welcome, <%= current_user.username %>!</li>
		  <li><%= link_to "Sign Out", signout_path %></li>
    <% else %>
		  <li><%= link_to "Sign In", signin_path %></li>
    <% end %>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/admin' %>
  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/_user.html.erb
	<li>
    <%= link_to user.username, user %>
    <% if current_user && current_user.admin? %>
      <% if user.roles %>
        | <strong>Roles:</strong> <%= user.roles.join(", ").titleize %>
      <% end %>
      | <%= link_to "Edit", edit_user_path(user) %> 
      | <%= link_to "Remove", user, :method => :delete, :confirm => "Are you sure?" %>
    <% end %>
  </li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render :partial => "form" %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>